### ISSUE TITLE
[Add Button / SSH addon] adding an array as value to commands key not possible

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/Jane#108]
The ssh addon requires the commands_parameter hash to have a key "commands" and an array as value. The array contains all commands that should be run.
Currently its not possible to add an array as value via the webinterface.
Two ways to fix this come to mind.
1. make it possible for the value to be an array via webui. This would result in a more complex ui.
2. let the addon run only one command. For multiple ssh commands you could create multiple commands in the ui (klick the add command button). The result is that for every command a new ssh session is created.

@Lyr3x : I think I'd go with option 2. Your thoughts?

**Comment by Lyr3x** [comment]
Im completly with you. Option 2 lgtm

Nesurion <notifications@github.com> schrieb am Sa., 18. Juli 2015 11:43:

**Comment by Nesurion** [comment]
done with #110
