### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/jane#114]
Ill create a navbar where the user can add links to external sites, e.g. solar panel data graph page, router webinterface, or temperature logger...

**Comment by Nesurion** [comment]
OK but can we discuss position? A typical navbar is on the top because its a curtail part of the website. But we dont need any kind of site navigation right now. So I would suggest to but it either on the left/right side as a "pop out" or at the button in a footer

**Comment by Lyr3x** [comment]
yep, i will change it this weekend

**Comment by Lyr3x** [comment]
There is a problem with mobile devices. The Sidebar will toggle automatically on small screens. Dont know how to fix this

**Comment by Lyr3x** [comment]
New sidebar is working well 5dffdda56bc0f9afb401d5f37749b678c4a6a193

We need to talk about the creation of links. I have some ideas how to do this.
