### ISSUE TITLE
bigger buttons on mobile

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/jane#127]
Buttons should be big enough to press them even if you are drunk as a skunk. Less missklicks is always better. This would mean more scrolling of course, but in my opinion this is not a real issue.
But I think bigger buttons only make sense in mobile view.
@Lyr3x what do you think?

**Comment by Lyr3x** [comment]
yep! we should increase the buttonsize in the mobile view, but not too much

**Comment by Nesurion** [comment]
I feel like to buttons are bigger with the new design. Should we still increase them in size or di you think they are ok now @Lyr3x ?

**Comment by Lyr3x** [comment]
Same feeling here.. I dont think so

**Comment by Nesurion** [comment]
ok closing for now. we'll reopen if we change your minds.
