### ISSUE TITLE
optional addons

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/Jane#37]
make addons like sunset optional, so user can decide what to use (and config).
loading a missing/not needed config would result in errors (and overhead).

**Comment by Lyr3x** [comment]
a addon which need an other addon, should loud automaticly the second one.

**Comment by Nesurion** [comment]
Since every addon needs to be configured the user should activate the addon. 
But the user should get a warning if a dependencie is not configured.

**Comment by Nesurion** [comment]
this will be fixed by refactor branch. The commander will only load addons used in the config.json

**Comment by Nesurion** [comment]
done 2e25c7e130f29f47a6f7549c434f26fbb919a245
