### ISSUE TITLE
better command call in config.json

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/Jane#39]
user shouldnt have to write ruby code in config.json. This would also allow jane to use system instead of evil eval.
edit config values for a button maybe like this:
```json
{
  "name": "tv_power",
  "icon": "off",
  "btn_class": "btn-info",
  
  "fn_args": [
    "tv",
    "power"
  ],
  
  "commands": [
    {
      "type" : "irsend",
      "sleep_after_command" : 0,
      "command_parameter":
        {
          "receiving_device": "tv",
          "command": "KEY_POWER"
        }
    }
  ]
},
{
  "name": "powerdown",
  "icon": "off",
  "btn_class": "btn-info",
  
  "fn_args": [
    "action",
    "power"
  ],
  
  "commands": [
    {
      "type" : "irsend",
      "sleep_after_command" : 2,
      "command_parameter":
        {
          "receiving_device": "tv",
          "command": "KEY_POWER"
        }
    },
    {
      "type" : "powerpi",
      "sleep_after_command" : 0,
      "command_parameter":
        {
          "receiving_device": "desklamp",
          "command": "off"
        }
    },
  ]
}
```

@Lyr3x what do you think?

**Comment by Nesurion** [comment]
json
```
"command" : "off"
```
command is a bad naming, but I couldn't come up with anything better at this moment.

**Comment by Lyr3x** [comment]
You're right, i thin its better to write the config without ruby code too. 
And what about `"command" : "<device>off/on" `

**Comment by Nesurion** [comment]
I think "device on/off" after the command tag is harder to parse.

**Comment by Lyr3x** [comment]
What do you think about
`"command" : "power_on"`

you dont have the device name twice but obviously the user should see what the command do

**Comment by Nesurion** [comment]
I think two values like device and command are easier to parse and since powerpi controls radio switches only two states are possible, on or off. 
We should discuss better naming for the command tag rather than the value that follows.

**Comment by Nesurion** [comment]
done with merge #49
