### ISSUE TITLE
external sinatra config

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Jane#41]
lets create a external sinatra config.ru and a rakefile

**Comment by Nesurion** [comment]
rakefile will be implemented after mergins branch lighton-config.
but rake/whenwever are not working just yet.

**Comment by Lyr3x** [comment]
and the merge of sinatra-cache.

**Comment by Nesurion** [comment]
I think we should wait with merging cache until lighton is merged, because lighton contains a Rakefile.

**Comment by Nesurion** [comment]
merging is done. gogogo on config.ru and stuff

**Comment by Nesurion** [comment]
Is there a need for a config.ru? From a quick look at [this](http://www.sinatrarb.com/intro.html#Using%20a%20Classic%20Style%20Application%20with%20a%20config.ru) it looks to me that we don't need one.
