### ISSUE TITLE
ERROR NoMethodError: undefined method `bytesize' for

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Jane#61]
When using any button this error appears:
```/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/utils.rb:361:in `bytesize'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:152:in `block in finish'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:152:in `each'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:152:in `inject'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:152:in `finish'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:909:in `call!'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/home/jarvis/.rvm/gems/ruby-2.1.4/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/home/jarvis/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/home/jarvis/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/home/jarvis/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'```

**Comment by Nesurion** [comment]
Bug is caused by changes in the way commands are handelt now. 
```
get "/foo" do
  Command.run(command)
end
```
sinatra expects a string as return type, which `Command.run` doesn't deliver.
Quickfix commit fixes the return type, but causes the cache to deliver cached version on GET without executing the command.

So root problem is clear, but no real fix yet.

**Comment by Nesurion** [comment]
@Lyr3x can we just cache / (index.erb)?
