### ISSUE TITLE
routes without button

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/Jane#62]
create routes without a button in the UI.
This would give other system the option to execute actions or commands without disturbing the user in the UI.
Example Use Case:
if kodi activates screensaver -> /tv/off
kodi deactivates screensaver -> /tv/on & /avr/channel/bluetooth & /avr/channel/hdrocker (in my case I have to switch channels on avr so avr detects that its supposed to handle audio)
Currently im running the following script.
``` python
#!/usr/bin/env python
import urllib2
import time
urllib2.urlopen("http://192.168.2.25:4567/tv/power").read()
time.sleep(7)
urllib2.urlopen("http://192.168.2.25:4567/avr/channel/bluetooth").read()
time.sleep(1)
urllib2.urlopen("http://192.168.2.25:4567/avr/channel/hdrocker").read()
```

@Lyr3x do you think this is a feature worth implementing?

**Comment by Lyr3x** [comment]
this would be nice :cool: !
