### ISSUE TITLE
Use bootstrap toggle/switch button for radio sockets

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Jane#63]

**Comment by Nesurion** [comment]
In terms of nice interface this would be cool. But from a technical standpoint: we can't get the status of the radio controlled socket, which might result in a different state of the actual device and the information in the interface. 
Scenario: Toggel light button from off to on => jane radio module send signal => for whatever reason the radio socket doesn't catch the signal => Light is off, interface says light is on.
I'm closing this issue. @Lyr3x feel free to reopen if you don't agree.
