### ISSUE TITLE
rcswitch-Pi + wiringPi instead of PowerPi

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Jane#64]
Let use use rcswitch and wiringpi instead of powerpi, cause powerpi is package which use this two components and an external webinterface. We dont need this.

**Comment by Nesurion** [comment]
Totaly agree.

**Comment by Lyr3x** [comment]
to work with wiring pi following system changes are needed:
`gpio export 17 out` (inside crontab)
`sudo usermod -a -G gpio userName`

**Comment by Nesurion** [comment]
we need to have wiringpi installed aswell right?

**Comment by Lyr3x** [comment]
+

**Comment by Lyr3x** [comment]
done and merged with #72
