### ISSUE TITLE
Use ajax for timer

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Jane#79]
use ajax for the new timer function

**Comment by Nesurion** [comment]
Sorry forgot: why did we wanted to do this?

**Comment by Lyr3x** [comment]
Remember what ajax is for. (redirect+timer)

**Comment by Nesurion** [comment]
I know what ajax is, but why should we use it? the only negativ aspect i see is that a call on the timer endpoint returns the index.html

**Comment by Nesurion** [comment]
done #82
