### ISSUE TITLE
scheduler function

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/jane#81]
build a scheduler addon and userinterface itegration to generate jobs that run on a regular basis.
Example: power off the light every weekday at 10pm.

**Comment by Nesurion** [comment]
oh boy! This will be quite a task I think. How it would work:
- Interface or call to api endpoint (contains device, action and time_to_run_at)
- scheduler.rb addon creates/deletes/modifys entry in schedule.rb (whenever)
- scheduler.rb addon creates/deletes/modifys entry in Rakefile
- scheduler.rb addon runs update_cron task
The tricky part: read, parse and modify schedule.rb and Rakefile.

**Comment by Lyr3x** [comment]
its done right? @Nesurion

**Comment by Nesurion** [comment]
Jap basics are done
