### ISSUE TITLE
Switch to Material Design Interface

### ISSUE THREAD

**Issue by Nesurion** [Lyr3x/Jane#86]
We could switch our css theme to material design with this:
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html
thanks @zod1ac for the tipp :)

**Comment by Lyr3x** [comment]
we should try this

**Comment by Nesurion** [comment]
see the material-design branch

**Comment by Nesurion** [comment]
We'll use the old design for now, maybe switch at some point in the future.
